version: "3.7"

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/frontend
    ports:
      - 8000:8000
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    depends_on:
      - db  
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - 5000:5000
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dev_db
  pgadmin:
    image: dpage/pgadmin4
    networks:
      - default
    depends_on: 
      - db

volumes:
  postgres_data:
