version: "3.7"

services:
    # frontend:
    #     env_file: .env
    #     image: python:3.7
    #     build: ./frontend
    #     command: ['frontend/run.sh']
    #     ports:
    #         - 8000:8000
    #     depends_on: backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    # depends_on:
    #   - db  
    volumes:
      - ./backend:/usr/src/backend
    # ports:
    #   - 5000:5000
#   db:
#     image: postgres:12-alpine
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     ports:
#       - "5432:5432"
#     environment:
#       - POSTGRES_USER=root
#       - POSTGRES_PASSWORD=admin
#       - POSTGRES_DB=dev_db

# volumes:
#   postgres_data:
