name: build_frontend

on: 
  # pull_request:
    # branches:
    # - master
    # paths:
    # - 'frontend/**'  
  push:
    # paths:
    # - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7' ]

    steps:
    - name: STEP 1. Check out repo
      uses: actions/checkout@v2
    #===============================================#
    - name: STEP 2. Set up Python {{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    #===============================================#
    - name: STEP 3. Install pipenv dependencies
      run: 
        working-directory: frontend
        |
        cd frontend
        python -m pip install --upgrade pip
        pip install pipenv
        python -m pipenv install --dev --system
    #===============================================#
    - name: STEP 4. Lint with black and flake8
      run: |
        pipenv run black --line-length=79 btc_dash
        pipenv run flake8 btc_dash
    #===============================================#
    - name: STEP 5. Test with pytest
      run: |
        coverage run --omit */.virtualenvs/* -m pytest
    #===============================================#
    - name: STEP 6. Generate coverage reports
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        coveralls
